name: Wake Up Render Site

on:
  schedule:
    # Runs every 14 minutes to prevent Render from spinning down
    - cron: '*/14 * * * *'
  workflow_dispatch: # Allows you to run it manually from the GitHub Actions tab

jobs:
  ping-site:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to Render
        run: |
          curl -Is https://one4-sports-7mg6.onrender.com
 | head -n 1
