name: Keep App Alive
on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
  workflow_dispatch: # Allows you to run it manually from the GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the application
        run: curl -s https://one4-sports-7mg6.onrender.com > /dev/null